### ISSUE TITLE
Client crashed because of hunter's pet

### ISSUE THREAD

**Issue by hbltth** [redmagejoe/TurtleHD#17] opened 2023-12-06 00:29 UTC
Hi sometimes my client crashed on the character selection page when I tried to choose my Tauren Hunter and the pet wasn't dismissed, a error frame was popped up. If pet was dismissed the crash would not occur.

**Comment by hbltth** [comment] 2023-12-08 21:45
I found it happens when I switch between my Warlock and Hunter.

**Comment by hbltth** [comment] 2023-12-15 21:53
Hunter's pet conflict with Warlock's pet I think.

**Comment by redmagejoe** [comment] 2023-12-25 10:32
Need to look into this.  Male Taurens in particular cause a number of issues on the character select screen, especially with the high-poly Scythe of Elune model.  It seems to be related to too many moving elements and a lack of sufficient memory allocated to the client.

**Comment by redmagejoe** [comment] 2024-06-24 11:11
Duplicate of or related to #7

**Closed by redmagejoe** 2024-06-24 11:11 UTC
